### ISSUE TITLE
need help. 

### ISSUE THREAD

**Issue by monicakumari** [Acosix/alfresco-simple-content-stores#14]
Hi Axel, 
Angel borroy told me that you can help me with my issue and he gave me this link on IRC. logs: [https://chat.alfresco.com/log_hash-alfresco_2018-05-24.html](url)

I had a running instance where contentstore is local, means all files were getting saved in alfresco_instance/alf_data/contentstore. Now I have changed the contentstore of that instance to azure container. I have copied all the data from contentstore in alfresco_instance/alf_data/contentstore location to the new azure container. but system is not starting up.

stacktrace errors in catalina.out : 

> 2018-05-24 13:29:55,167  INFO  [domain.schema.SchemaBootstrap] [localhost-startStop-1] No changes were made to the schema.
 2018-05-24 13:29:56,126  ERROR [web.context.ContextLoader] [localhost-startStop-1] Context initialization failed
 org.alfresco.error.AlfrescoRuntimeException: 04240001 Failed to bootstrap tenants
    at org.alfresco.repo.tenant.MultiTAdminServiceImpl.startTenants(MultiTAdminServiceImpl.java:372)
    at org.alfresco.repo.tenant.MultiTenantBootstrap.onBootstrap(MultiTenantBootstrap.java:73)
    at org.springframework.extensions.surf.util.AbstractLifecycleBean.onApplicationEvent(AbstractLifecycleBean.java:56)
    at org.alfresco.repo.management.SafeApplicationEventMulticaster.multicastEventInternal(SafeApplicationEventMulticaster.java:214)
    at org.alfresco.repo.management.SafeApplicationEventMulticaster.multicastEvent(SafeApplicationEventMulticaster.java:185)
    at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:334)
    at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:954)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:482)
    at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:410)
    at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
    at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112)
    at org.alfresco.web.app.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:70)
    at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5118)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5634)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:899)
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:875)
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
    at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:679)
    at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1966)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:748)
Caused by: org.alfresco.error.AlfrescoRuntimeException: 04240000 MT: cannot start tenants - TenantRoutingContentStore is not configured AND not all tenants use co-mingled content store
    at org.alfresco.repo.tenant.MultiTAdminServiceImpl.startTenants(MultiTAdminServiceImpl.java:328)
    ... 24 more
May 24, 2018 1:29:56 PM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Exception sending context initialized event to listener instance of class org.alfresco.web.app.ContextLoaderListener
org.alfresco.error.AlfrescoRuntimeException: 04240001 Failed to bootstrap tenants
    at org.alfresco.repo.tenant.MultiTAdminServiceImpl.startTenants(MultiTAdminServiceImpl.java:372)
    at org.alfresco.repo.tenant.MultiTenantBootstrap.onBootstrap(MultiTenantBootstrap.java:73)
    at org.springframework.extensions.surf.util.AbstractLifecycleBean.onApplicationEvent(AbstractLifecycleBean.java:56)
    at org.alfresco.repo.management.SafeApplicationEventMulticaster.multicastEventInternal(SafeApplicationEventMulticaster.java:214)
    at org.alfresco.repo.management.SafeApplicationEventMulticaster.multicastEvent(SafeApplicationEventMulticaster.java:185)
    at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:334)
    at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:954)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:482)
    at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:410)
    at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
    at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112)
    at org.alfresco.web.app.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:70)
    at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5118)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5634)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:899)
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:875)
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
    at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:679)
    at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1966)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:748)
Caused by: org.alfresco.error.AlfrescoRuntimeException: 04240000 MT: cannot start tenants - TenantRoutingContentStore is not configured AND not all tenants use co-mingled content store
    at org.alfresco.repo.tenant.MultiTAdminServiceImpl.startTenants(MultiTAdminServiceImpl.java:328)
    ... 24 more
> May 24, 2018 1:29:56 PM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Exception sending context initialized event to listener instance of class org.alfresco.web.app.ContextListener
org.alfresco.error.AlfrescoRuntimeException: 04240001 Failed to bootstrap tenants
    at org.alfresco.repo.tenant.MultiTAdminServiceImpl.startTenants(MultiTAdminServiceImpl.java:372)
    at org.alfresco.repo.tenant.MultiTenantBootstrap.onBootstrap(MultiTenantBootstrap.java:73)
    at org.springframework.extensions.surf.util.AbstractLifecycleBean.onApplicationEvent(AbstractLifecycleBean.java:56)
    at org.alfresco.repo.management.SafeApplicationEventMulticaster.multicastEventInternal(SafeApplicationEventMulticaster.java:214)
    at org.alfresco.repo.management.SafeApplicationEventMulticaster.multicastEvent(SafeApplicationEventMulticaster.java:185)
    at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:334)
    at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:954)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:482)
    at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:410)
    at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
    at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112)
    at org.alfresco.web.app.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:70)
    at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5118)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5634)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:899)
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:875)
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
    at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:679)
    at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1966)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:748)
Caused by: org.alfresco.error.AlfrescoRuntimeException: 04240000 MT: cannot start tenants - TenantRoutingContentStore is not configured AND not all tenants use co-mingled content store
    at org.alfresco.repo.tenant.MultiTAdminServiceImpl.startTenants(MultiTAdminServiceImpl.java:328)
    ... 24 more
 
> May 24, 2018 1:29:56 PM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Exception sending context initialized event to listener instance of class org.alfresco.repo.webdav.WebDAVSessionListener
org.alfresco.error.AlfrescoRuntimeException: 04240001 Failed to bootstrap tenants
    at org.alfresco.repo.tenant.MultiTAdminServiceImpl.startTenants(MultiTAdminServiceImpl.java:372)
    at org.alfresco.repo.tenant.MultiTenantBootstrap.onBootstrap(MultiTenantBootstrap.java:73)
    at org.springframework.extensions.surf.util.AbstractLifecycleBean.onApplicationEvent(AbstractLifecycleBean.java:56)
    at org.alfresco.repo.management.SafeApplicationEventMulticaster.multicastEventInternal(SafeApplicationEventMulticaster.java:214)
    at org.alfresco.repo.management.SafeApplicationEventMulticaster.multicastEvent(SafeApplicationEventMulticaster.java:185)
    at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:334)
    at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:954)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:482)
    at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:410)
    at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
    at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112)
    at org.alfresco.web.app.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:70)
    at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5118)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5634)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:899)
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:875)
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
    at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:679)
    at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1966)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:748)
Caused by: org.alfresco.error.AlfrescoRuntimeException: 04240000 MT: cannot start tenants - TenantRoutingContentStore is not configured AND not all tenants use co-mingled content store
    at org.alfresco.repo.tenant.MultiTAdminServiceImpl.startTenants(MultiTAdminServiceImpl.java:328)
    ... 24 more
> May 24, 2018 1:29:56 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: One or more listeners failed to start. Full details will be found in the appropriate container log file
May 24, 2018 1:29:56 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/alfresco] startup failed due to previous errors
May 24, 2018 1:29:56 PM org.apache.catalina.core.ApplicationContext log
INFO: Closing Spring root WebApplicationContext
2018-05-24 13:29:56,363  WARN  [context.support.XmlWebApplicationContext] [localhost-startStop-1] Exception thrown from ApplicationListener handling ContextClosedEvent
 java.lang.NullPointerException
    at org.alfresco.repo.workflow.activiti.ActivitiEngineInitializer.onShutdown(ActivitiEngineInitializer.java:65)
    at org.springframework.extensions.surf.util.AbstractLifecycleBean.onApplicationEvent(AbstractLifecycleBean.java:67)
    at org.alfresco.repo.management.SafeApplicationEventMulticaster.multicastEventInternal(SafeApplicationEventMulticaster.java:214)
    at org.alfresco.repo.management.SafeApplicationEventMulticaster.multicastEvent(SafeApplicationEventMulticaster.java:190)
    at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:334)
    at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1055)
    at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1016)
    at org.springframework.web.context.ContextLoader.closeWebApplicationContext(ContextLoader.java:586)
    at org.springframework.web.context.ContextLoaderListener.contextDestroyed(ContextLoaderListener.java:143)
    at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:5165)
    at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5829)
    at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:221)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:149)
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:899)
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:875)
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
    at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:679)
    at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1966)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:748)
2018-05-24 13:29:56,639  INFO  [management.subsystems.ChildApplicationContextFactory] [localhost-startStop-1] Stopping 'ContentStore' subsystem, ID: [ContentStore, managed, unencrypted]
 2018-05-24 13:29:56,639  INFO  [management.subsystems.ChildApplicationContextFactory] [localhost-startStop-1] Stopped 'ContentStore' subsystem, ID: [ContentStore, managed, unencrypted]
 2018-05-24 13:29:56,900  INFO  [management.subsystems.ChildApplicationContextFactory] [localhost-startStop-1] Stopping 'Transformers' subsystem, ID: [Transformers, default]
 2018-05-24 13:29:56,900  INFO  [management.subsystems.ChildApplicationContextFactory] [localhost-startStop-1] Stopped 'Transformers' subsystem, ID: [Transformers, default]
 2018-05-24 13:29:56,901  INFO  [management.subsystems.ChildApplicationContextFactory] [localhost-startStop-1] Stopping 'Authentication' subsystem, ID: [Authentication, managed, alfrescoNtlm1]
 2018-05-24 13:29:56,901  INFO  [management.subsystems.ChildApplicationContextFactory] [localhost-startStop-1] Stopped 'Authentication' subsystem, ID: [Authentication, managed, alfrescoNtlm1]
 2018-05-24 13:29:56,905  WARN  [factory.support.DisposableBeanAdapter] [localhost-startStop-1] Invocation of destroy method 'shutdown' failed on bean with name 'standardQuotaManager': org.alfresco.service.cmr.repository.ContentIOException: 04240003 Failed to open stream onto channel:
   writer: ContentAccessor[ contentUrl=store:///home/alfresco_installer/eisenvault_installations/local_instance/alf_data/cachedcontent/cache-usage.txt, mimetype=null, size=1, encoding=UTF-8, locale=en_IN]
 May 24, 2018 1:29:56 PM org.apache.catalina.core.ApplicationContext log
INFO: Shutting down log4j
May 24, 2018 1:29:56 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [/alfresco] appears to have started a thread named [CachedContentCleaner] but has failed to stop it. This is very likely to create a memory leak.
May 24, 2018 1:29:56 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [/alfresco] appears to have started a thread named [Timer-1] but has failed to stop it. This is very likely to create a memory leak.
May 24, 2018 1:29:56 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [/alfresco] appears to have started a thread named [Timer-2] but has failed to stop it. This is very likely to create a memory leak.
May 24, 2018 1:29:56 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [/alfresco] appears to have started a thread named [Timer-3] but has failed to stop it. This is very likely to create a memory leak.
May 24, 2018 1:29:56 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [/alfresco] appears to have started a thread named [Timer-4] but has failed to stop it. This is very likely to create a memory leak.
May 24, 2018 1:29:56 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [/alfresco] appears to have started a thread named [Timer-5] but has failed to stop it. This is very likely to create a memory leak.
May 24, 2018 1:29:56 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [/alfresco] appears to have started a thread named [Timer-6] but has failed to stop it. This is very likely to create a memory leak.
May 24, 2018 1:29:56 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [/alfresco] appears to have started a thread named [Timer-7] but has failed to stop it. This is very likely to create a memory leak.
May 24, 2018 1:29:56 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [/alfresco] appears to have started a thread named [Timer-8] but has failed to stop it. This is very likely to create a memory leak.
May 24, 2018 1:29:56 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [/alfresco] appears to have started a thread named [Timer-9] but has failed to stop it. This is very likely to create a memory leak.
May 24, 2018 1:29:56 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [/alfresco] appears to have started a thread named [Timer-10] but has failed to stop it. This is very likely to create a memory leak.
May 24, 2018 1:29:56 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [/alfresco] appears to have started a thread named [Timer-11] but has failed to stop it. This is very likely to create a memory leak.
May 24, 2018 1:29:56 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [/alfresco] appears to have started a thread named [Timer-12] but has failed to stop it. This is very likely to create a memory leak.
May 24, 2018 1:29:56 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [/alfresco] appears to have started a thread named [Timer-13] but has failed to stop it. This is very likely to create a memory leak.
May 24, 2018 1:29:56 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [/alfresco] appears to have started a thread named [Timer-14] but has failed to stop it. This is very likely to create a memory leak.
May 24, 2018 1:29:56 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [/alfresco] appears to have started a thread named [Timer-15] but has failed to stop it. This is very likely to create a memory leak.
May 24, 2018 1:29:56 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [/alfresco] appears to have started a thread named [Timer-16] but has failed to stop it. This is very likely to create a memory leak.
May 24, 2018 1:29:56 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [/alfresco] appears to have started a thread named [Timer-17] but has failed to stop it. This is very likely to create a memory leak.
May 24, 2018 1:29:56 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [/alfresco] appears to have started a thread named [Timer-18] but has failed to stop it. This is very likely to create a memory leak.
May 24, 2018 1:29:56 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [/alfresco] appears to have started a thread named [Timer-19] but has failed to stop it. This is very likely to create a memory leak.
May 24, 2018 1:29:56 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [/alfresco] appears to have started a thread named [Timer-20] but has failed to stop it. This is very likely to create a memory leak.
May 24, 2018 1:29:56 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [/alfresco] appears to have started a thread named [Timer-21] but has failed to stop it. This is very likely to create a memory leak.
May 24, 2018 1:29:56 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [/alfresco] appears to have started a thread named [Timer-22] but has failed to stop it. This is very likely to create a memory leak.
May 24, 2018 1:29:56 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [/alfresco] appears to have started a thread named [Timer-23] but has failed to stop it. This is very likely to create a memory leak.
May 24, 2018 1:29:56 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
> SEVERE: The web application [/alfresco] appears to have started a thread named [Timer-24] but has failed to stop it. This is very likely to create a memory leak.
May 24, 2018 1:29:56 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [/alfresco] appears to have started a thread named [Timer-25] but has failed to stop it. This is very likely to create a memory leak.
May 24, 2018 1:29:56 PM org.apache.catalina.loader.WebappClassLoaderBase checkThreadLocalMapForLeaks
SEVERE: The web application [/alfresco] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@3f5fe26e]) and a value of type [org.alfresco.util.CachingDateFormat] (value [yyyy-MM-dd]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
May 24, 2018 1:29:56 PM org.apache.catalina.loader.WebappClassLoaderBase checkThreadLocalMapForLeaks
SEVERE: The web application [/alfresco] created a ThreadLocal with key of type [org.alfresco.repo.template.QNameAwareObjectWrapper$1] (value [org.alfresco.repo.template.QNameAwareObjectWrapper$1@76a0ebad]) and a value of type [org.alfresco.repo.template.QNameAwareObjectWrapper$1$1] (value [org.alfresco.repo.template.QNameAwareObjectWrapper$1$1@349e19b]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
May 24, 2018 1:29:56 PM org.apache.catalina.loader.WebappClassLoaderBase checkThreadLocalMapForLeaks
SEVERE: The web application [/alfresco] created a ThreadLocal with key of type [org.alfresco.repo.template.QNameAwareObjectWrapper$1] (value [org.alfresco.repo.template.QNameAwareObjectWrapper$1@29901cd1]) and a value of type [org.alfresco.repo.template.QNameAwareObjectWrapper$1$1] (value [org.alfresco.repo.template.QNameAwareObjectWrapper$1$1@589c67cd]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
May 24, 2018 1:29:56 PM org.apache.catalina.loader.WebappClassLoaderBase checkThreadLocalMapForLeaks
SEVERE: The web application [/alfresco] created a ThreadLocal with key of type [org.alfresco.repo.template.QNameAwareObjectWrapper$1] (value [org.alfresco.repo.template.QNameAwareObjectWrapper$1@1415007c]) and a value of type [org.alfresco.repo.template.QNameAwareObjectWrapper$1$1] (value [org.alfresco.repo.template.QNameAwareObjectWrapper$1$1@7ec260af]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
May 24, 2018 1:29:56 PM org.apache.catalina.startup.HostConfig deployDescriptor
INFO: Deployment of configuration descriptor /home/alfresco_installer/eisenvault_installations/local_instance/tomcat/conf/Catalina/localhost/alfresco.xml has finished in 30,045 ms
May 24, 2018 1:29:56 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive /home/alfresco_installer/eisenvault_installations/local_instance/tomcat/webapps/ROOT.war
May 24, 2018 1:29:56 PM org.apache.catalina.startup.SetContextPropertiesRule begin
WARNING: [SetContextPropertiesRule]{Context} Setting property 'debug' to '100' did not find a matching property.
May 24, 2018 1:29:57 PM org.apache.catalina.startup.TldConfig execute
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
May 24, 2018 1:29:57 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deployment of web application archive /home/alfresco_installer/eisenvault_installations/local_instance/tomcat/webapps/ROOT.war has finished in 56 ms
May 24, 2018 1:29:57 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive /home/alfresco_installer/eisenvault_installations/local_instance/tomcat/webapps/_vti_bin.war
May 24, 2018 1:29:57 PM org.apache.catalina.startup.TldConfig execute
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
May 24, 2018 1:29:57 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deployment of web application archive /home/alfresco_installer/eisenvault_installations/local_instance/tomcat/webapps/_vti_bin.war has finished in 106 ms
May 24, 2018 1:29:57 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory /home/alfresco_installer/eisenvault_installations/local_instance/tomcat/webapps/manager
May 24, 2018 1:29:57 PM org.apache.catalina.startup.TldConfig execute
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
May 24, 2018 1:29:57 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deployment of web application directory /home/alfresco_installer/eisenvault_installations/local_instance/tomcat/webapps/manager has finished in 55 ms
May 24, 2018 1:29:57 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory /home/alfresco_installer/eisenvault_installations/local_instance/tomcat/webapps/host-manager
May 24, 2018 1:29:57 PM org.apache.catalina.startup.TldConfig execute
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
May 24, 2018 1:29:57 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deployment of web application directory /home/alfresco_installer/eisenvault_installations/local_instance/tomcat/webapps/host-manager has finished in 73 ms
May 24, 2018 1:29:57 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-apr-8080"]
May 24, 2018 1:29:57 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["ajp-apr-8009"]
May 24, 2018 1:29:57 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-bio-8443"]
May 24, 2018 1:29:57 PM org.apache.catalina.startup.Catalina start
INFO: Server startup in 49068 ms
2018-05-24 13:29:57,450  ERROR [solr.tracker.AbstractTracker] [org.alfresco.solr.AlfrescoCoreAdminHandler@2758c927_Worker-1] Model tracking failed
 org.alfresco.error.AlfrescoRuntimeException: 04240000 GetModelsDiff return status is 404
    at org.alfresco.solr.client.SOLRAPIClient.getModelsDiff(SOLRAPIClient.java:1181)
    at org.alfresco.solr.tracker.ModelTracker.trackModelsImpl(ModelTracker.java:256)
    at org.alfresco.solr.tracker.ModelTracker.trackModels(ModelTracker.java:214)
    at org.alfresco.solr.tracker.ModelTracker.ensureFirstModelSync(ModelTracker.java:236)
    at org.alfresco.solr.tracker.CoreWatcherJob.registerForCore(CoreWatcherJob.java:145)
    at org.alfresco.solr.tracker.CoreWatcherJob.execute(CoreWatcherJob.java:82)
    at org.quartz.core.JobRunShell.run(JobRunShell.java:216)
    at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:563)

Angel said : It looks like CachingContentStore is a TenantAware interface. probably this changed in last releases

I need your help in this. what could be the solution.

Thanks.

**Comment by AFaust** [comment]
Looking at the IRC log, Angel primarily pointed you to this addon just to show that I am quite involved / knowledgeable when it comes to the content store part of the Alfresco architecture. You could have also asked me in IRC - I just wasn't online yesterday as I was at a customer workshop.

Anyway: Angel is correct - the CachingContentStore is not a tenant-aware content store, and at least one of your tenants has been created with a specific content store directory that does not match the content store location of the backing store, which I assume is the Azure store, so does not actually have a physical location in the local filesystem.
It's actually stupid, but with default Alfresco content stores, you cannot use a non-filesystem content store once you have created tenants. With my addon (this alfresco-simple-content-stores) I have actually implemented the content stores in such a way that they should be compatible with multi-tenancy (even when the primary content store is working with something like Azure or S3), as long as at least one secondary content store is a TenantRoutingContentStore. Unfortunately, at this time the https://addons.alfresco.com/addons/azure-block-blob-storage-adapter-alfresco is not compatible with my addon and I did not have time yet to implement my own Azure / S3 variants as part of my addon.

**Comment by AFaust** [comment]
In the meantime, you may be able to work around this by using Azure Files instead of just the Blob storage, and [mount Azure Files as a local filesystem in your server](https://docs.microsoft.com/de-de/azure/storage/files/storage-how-to-use-files-linux), using the same location as your previous content store.

**Comment by monicakumari** [comment]
Thanks for your reply. 
Axel,  how much effort it will take ?

**Comment by AFaust** [comment]
Which part specifically? The part about integrating Azure / S3 variants in my addon or you switching to Azure Files? The former is about a day and a half for each variant, though the biggest problem at the moment is my available time as I am fully booked on my paid work with llittle time remaining for my open source projects. The latter depends on your profiency and the amount of data you have, if you need to re-copy the data.

**Comment by monicakumari** [comment]
I need your help in knowing latter part.
we are planning to move contentstore to azure container and would like to use container for all our new instances and migrate our old instances to azure container. 
moving data is not a big headache for us. I want to know about the part related to tenant migration
in both the cases
1. When the tenant have their data in the default contentstore
2. When the tenant data is located on a different location
What we need to do to make our contentstore tenant aware.

Please guide me in this. 

Thanks.

**Comment by AFaust** [comment]
The "latter" part is about switching to Azure Files - I have no experience for that, and also no estimate about the amount of data we are talking about here. I am not sure how I can help you in estimating that effort.

Re. 1) I don't unterstand the question in this case. The effort of copying data to Azure files should be the same regardless of whether tenant data is stored in the default contentstore or not. It is just a minor question of the logical separation via paths.

Re. 2) Again, the effort of migration is pretty much the same either way. The only thing you need to make sure is that the primary content store (default bean name "fileContentStore") implements the TenantRoutingContentStore interface.

If you are using Azure Files and mount it to your file system, the following aspects need to be considered
* the Alfresco default file content store is already compatible with having tenants
* the default content store location is configured simply via the dir.root property - if your tenant content is stored in the default content store, you would be done in this case....
* if any tenant has been created with a custom content store path (check your database alf_tenant table for content roots), you need to make sure that the corresponding contents in Azure files are either mounted to the same path in the file system, or that you change the content store path value in the database
