### ISSUE TITLE
addon for alfresco community 5.0.d

### ISSUE THREAD

**Issue by maciass2008** [Acosix/alfresco-simple-content-stores#15]
hello,
is your addon functional under the alfresco community 5.0.d version ? 
if yes can you help me please
when i generate the de.acosix.alfresco.simplecontentstores.repo-1.0.0.0-SNAPSHOT-installable.jar file
i put the following JARs  in the <tomcat>/webapps/alfresco/WEB-INF/lib:

    de.acosix.alfresco.utility.repo-1.0.2.1.jar
    de.acosix.alfresco.utility.common-1.0.2.1.jar
    de.acosix.alfresco.simplecontentstores.repo-1.0.0.0-SNAPSHOT-installable.jar
    xz-1.5.jar (3rd-party JAR for compression)
and i add the following lines into the alfresco-global.properties :

dir.root=D:/Alfresco/alf_data
simpleContentStores.enabled=true
simpleContentStores.customStores=myCustomFileStore
simpleContentStores.rootStore=myCustomFileStore
simpleContentStores.customStore.myCustomFileStore.type=standardFileStore
simpleContentStores.customStore.myCustomFileStore.value.rootDirectory=${dir.root}/myContentStore
simpleContentStores.customStore.myCustomFileStore.value.deleteEmptyDirs=true
simpleContentStores.customStore.myCustomFileStore.value.fixedLimit=104857600

=>> i can not authenticate when i restart alfresco and try to access to alfresco share page 

in the log files I have the following error:

`
2018-06-01 21:58:19 Commons Daemon procrun stderr initialized
juin 01, 2018 9:58:20 PM org.apache.catalina.core.AprLifecycleListener lifecycleEvent
INFOS: Loaded APR based Apache Tomcat Native library 1.1.32 using APR version 1.5.1.
juin 01, 2018 9:58:20 PM org.apache.catalina.core.AprLifecycleListener lifecycleEvent
INFOS: APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
juin 01, 2018 9:58:21 PM org.apache.catalina.core.AprLifecycleListener initializeSSL
INFOS: OpenSSL successfully initialized (OpenSSL 1.0.1j 15 Oct 2014)
juin 01, 2018 9:58:21 PM org.apache.coyote.AbstractProtocol init
INFOS: Initializing ProtocolHandler ["http-apr-8080"]
juin 01, 2018 9:58:21 PM org.apache.coyote.AbstractProtocol init
INFOS: Initializing ProtocolHandler ["ajp-apr-8009"]
juin 01, 2018 9:58:21 PM org.apache.coyote.AbstractProtocol init
INFOS: Initializing ProtocolHandler ["http-bio-8443"]
juin 01, 2018 9:58:22 PM org.apache.catalina.startup.Catalina load
INFOS: Initialization processed in 2003 ms
juin 01, 2018 9:58:22 PM org.apache.catalina.core.StandardService startInternal
INFOS: Démarrage du service Catalina
juin 01, 2018 9:58:22 PM org.apache.catalina.core.StandardEngine startInternal
INFOS: Starting Servlet Engine: Apache Tomcat/7.0.59
juin 01, 2018 9:58:22 PM org.apache.catalina.startup.HostConfig deployDescriptor
INFOS: Déploiement du descripteur de configuration D:\Alfresco\tomcat\conf\Catalina\localhost\solr4.xml
juin 01, 2018 9:58:22 PM org.apache.catalina.startup.SetContextPropertiesRule begin
AVERTISSEMENT: [SetContextPropertiesRule]{Context} Setting property 'debug' to '0' did not find a matching property.
juin 01, 2018 9:58:33 PM org.apache.catalina.startup.HostConfig deployDescriptor
INFOS: Deployment of configuration descriptor D:\Alfresco\tomcat\conf\Catalina\localhost\solr4.xml has finished in 11 338 ms
juin 01, 2018 9:58:33 PM org.apache.catalina.startup.HostConfig deployWAR
INFOS: Déploiement de l'archive D:\Alfresco\tomcat\webapps\alfresco.war de l'application web
juin 01, 2018 9:59:36 PM org.apache.catalina.core.StandardContext startInternal
GRAVE: Error listenerStart
juin 01, 2018 9:59:36 PM org.apache.catalina.core.StandardContext startInternal
GRAVE: Erreur de démarrage du contexte [/alfresco] suite aux erreurs précédentes
juin 01, 2018 9:59:38 PM org.apache.catalina.startup.HostConfig deployWAR
INFOS: Deployment of web application archive D:\Alfresco\tomcat\webapps\alfresco.war has finished in 65 238 ms
juin 01, 2018 9:59:38 PM org.apache.catalina.startup.HostConfig deployWAR
INFOS: Déploiement de l'archive D:\Alfresco\tomcat\webapps\share.war de l'application web
juin 01, 2018 9:59:53 PM org.apache.catalina.startup.HostConfig deployWAR
INFOS: Deployment of web application archive D:\Alfresco\tomcat\webapps\share.war has finished in 14 944 ms
juin 01, 2018 9:59:53 PM org.apache.catalina.startup.HostConfig deployDirectory
INFOS: Déploiement du répertoire D:\Alfresco\tomcat\webapps\host-manager de l'application web
juin 01, 2018 9:59:53 PM org.apache.catalina.startup.HostConfig deployDirectory
INFOS: Deployment of web application directory D:\Alfresco\tomcat\webapps\host-manager has finished in 107 ms
juin 01, 2018 9:59:53 PM org.apache.catalina.startup.HostConfig deployDirectory
INFOS: Déploiement du répertoire D:\Alfresco\tomcat\webapps\manager de l'application web
juin 01, 2018 9:59:53 PM org.apache.catalina.startup.HostConfig deployDirectory
INFOS: Deployment of web application directory D:\Alfresco\tomcat\webapps\manager has finished in 84 ms
juin 01, 2018 9:59:53 PM org.apache.coyote.AbstractProtocol start
INFOS: Starting ProtocolHandler ["http-apr-8080"]
juin 01, 2018 9:59:53 PM org.apache.coyote.AbstractProtocol start
INFOS: Starting ProtocolHandler ["ajp-apr-8009"]
juin 01, 2018 9:59:53 PM org.apache.coyote.AbstractProtocol start
INFOS: Starting ProtocolHandler ["http-bio-8443"]
juin 01, 2018 9:59:53 PM org.apache.catalina.startup.Catalina start
INFOS: Server startup in 91892 ms
ady defined
juin 01, 2018 9:58:44 PM org.apache.catalina.startup.TaglibUriRule body
INFOS: TLD skipped. URI: http://java.sun.com/jstl/xml is already defined
juin 01, 2018 9:58:44 PM org.apache.catalina.startup.TaglibUriRule body
INFOS: TLD skipped. URI: http://java.sun.com/jsp/jstl/xml is already defined
juin 01, 2018 9:58:44 PM org.apache.catalina.core.ApplicationContext log
INFOS: No Spring WebApplicationInitializer types detected on classpath
log4j:ERROR Could not find value for key log4j.appender.error
log4j:ERROR Could not instantiate appender named "error".
juin 01, 2018 9:58:44 PM org.apache.catalina.core.ApplicationContext log
INFOS: Initializing Spring root WebApplicationContext
juin 01, 2018 9:59:29 PM org.apache.catalina.core.StandardContext listenerStart
GRAVE: Exception lors de l'envoi de l'évènement contexte initialisé (context initialized) à l'instance de classe d'écoute (listener) org.alfresco.web.app.ContextLoaderListener
org.alfresco.error.AlfrescoRuntimeException: 05010001 Ensure that the 'dir.root' property is pointing to the correct data location.
	at org.alfresco.repo.admin.ConfigurationChecker.check(ConfigurationChecker.java:256)
	at org.alfresco.repo.admin.ConfigurationChecker.access$000(ConfigurationChecker.java:64)
	at org.alfresco.repo.admin.ConfigurationChecker$1$1.doWork(ConfigurationChecker.java:179)
	at org.alfresco.repo.security.authentication.AuthenticationUtil.runAs(AuthenticationUtil.java:548)
	at org.alfresco.repo.admin.ConfigurationChecker$1.execute(ConfigurationChecker.java:175)
	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:457)
	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:345)
	at org.alfresco.repo.admin.ConfigurationChecker.onBootstrap(ConfigurationChecker.java:185)
	at org.springframework.extensions.surf.util.AbstractLifecycleBean.onApplicationEvent(AbstractLifecycleBean.java:56)
	at org.alfresco.repo.management.SafeApplicationEventMulticaster.multicastEventInternal(SafeApplicationEventMulticaster.java:209)
	at org.alfresco.repo.management.SafeApplicationEventMulticaster.multicastEvent(SafeApplicationEventMulticaster.java:180)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:334)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:948)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:482)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:410)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112)
	at org.alfresco.web.app.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:63)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5016)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5524)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1081)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1877)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

juin 01, 2018 9:59:29 PM org.apache.catalina.core.StandardContext listenerStart
GRAVE: Exception lors de l'envoi de l'évènement contexte initialisé (context initialized) à l'instance de classe d'écoute (listener) org.alfresco.web.app.ContextListener
org.alfresco.error.AlfrescoRuntimeException: 05010001 Ensure that the 'dir.root' property is pointing to the correct data location.
	at org.alfresco.repo.admin.ConfigurationChecker.check(ConfigurationChecker.java:256)
	at org.alfresco.repo.admin.ConfigurationChecker.access$000(ConfigurationChecker.java:64)
	at org.alfresco.repo.admin.ConfigurationChecker$1$1.doWork(ConfigurationChecker.java:179)
	at org.alfresco.repo.security.authentication.AuthenticationUtil.runAs(AuthenticationUtil.java:548)
	at org.alfresco.repo.admin.ConfigurationChecker$1.execute(ConfigurationChecker.java:175)
	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:457)
	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:345)
	at org.alfresco.repo.admin.ConfigurationChecker.onBootstrap(ConfigurationChecker.java:185)
	at org.springframework.extensions.surf.util.AbstractLifecycleBean.onApplicationEvent(AbstractLifecycleBean.java:56)
	at org.alfresco.repo.management.SafeApplicationEventMulticaster.multicastEventInternal(SafeApplicationEventMulticaster.java:209)
	at org.alfresco.repo.management.SafeApplicationEventMulticaster.multicastEvent(SafeApplicationEventMulticaster.java:180)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:334)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:948)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:482)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:410)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112)
	at org.alfresco.web.app.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:63)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5016)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5524)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1081)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1877)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

juin 01, 2018 9:59:29 PM org.apache.catalina.core.StandardContext listenerStart
GRAVE: Exception lors de l'envoi de l'évènement contexte initialisé (context initialized) à l'instance de classe d'écoute (listener) org.alfresco.repo.webdav.WebDAVSessionListener
org.alfresco.error.AlfrescoRuntimeException: 05010001 Ensure that the 'dir.root' property is pointing to the correct data location.
	at org.alfresco.repo.admin.ConfigurationChecker.check(ConfigurationChecker.java:256)
	at org.alfresco.repo.admin.ConfigurationChecker.access$000(ConfigurationChecker.java:64)
	at org.alfresco.repo.admin.ConfigurationChecker$1$1.doWork(ConfigurationChecker.java:179)
	at org.alfresco.repo.security.authentication.AuthenticationUtil.runAs(AuthenticationUtil.java:548)
	at org.alfresco.repo.admin.ConfigurationChecker$1.execute(ConfigurationChecker.java:175)
	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:457)
	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:345)
	at org.alfresco.repo.admin.ConfigurationChecker.onBootstrap(ConfigurationChecker.java:185)
	at org.springframework.extensions.surf.util.AbstractLifecycleBean.onApplicationEvent(AbstractLifecycleBean.java:56)
	at org.alfresco.repo.management.SafeApplicationEventMulticaster.multicastEventInternal(SafeApplicationEventMulticaster.java:209)
	at org.alfresco.repo.management.SafeApplicationEventMulticaster.multicastEvent(SafeApplicationEventMulticaster.java:180)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:334)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:948)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:482)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:410)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112)
	at org.alfresco.web.app.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:63)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5016)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5524)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1081)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1877)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

juin 01, 2018 9:59:29 PM com.sun.xml.ws.transport.http.servlet.WSServletContextListener contextInitialized
INFOS: WSSERVLET12: JAX-WS context listener initializing
juin 01, 2018 9:59:35 PM com.sun.xml.ws.transport.http.servlet.WSServletDelegate <init>
INFOS: WSSERVLET14: JAX-WS servlet initializing
juin 01, 2018 9:59:36 PM com.sun.xml.ws.transport.http.servlet.WSServletDelegate destroy
INFOS: WSSERVLET15: JAX-WS servlet destroyed
juin 01, 2018 9:59:36 PM com.sun.xml.ws.transport.http.servlet.WSServletContextListener contextDestroyed
INFOS: WSSERVLET13: JAX-WS context listener destroyed
juin 01, 2018 9:59:36 PM org.apache.catalina.core.ApplicationContext log
INFOS: Closing Spring root WebApplicationContext
juin 01, 2018 9:59:38 PM org.apache.catalina.core.ApplicationContext log
INFOS: Shutting down log4j
juin 01, 2018 9:59:41 PM org.apache.catalina.core.ApplicationContext log
INFOS: No Spring WebApplicationInitializer types detected on classpath
juin 01, 2018 9:59:41 PM org.apache.catalina.core.ApplicationContext log
INFOS: Initializing Spring root WebApplicationContext
juin 01, 2018 9:59:53 PM org.apache.catalina.core.ApplicationContext log
INFOS: org.tuckey.web.filters.urlrewrite.UrlRewriteFilter INFO: loaded (conf ok)
juin 01, 2018 9:59:53 PM org.apache.catalina.core.ApplicationContext log
INFOS: Initializing Spring FrameworkServlet 'Spring Surf Dispatcher Servlet'
`
Have you any suggestion?

**Comment by AFaust** [comment]
The addon is functional under the 5.0 release, provided you build it from the [proper branch for Alfresco 5.0 + 5.1](https://github.com/Acosix/alfresco-simple-content-stores/tree/alfresco-5.0).

Did you install the addon in an already existing system which already had data in it? Is the value for "dir.root" that you have set pointing to an existing folder?
That error typically comes when you change the content stores of an existing system without properly moving / copying the old contents, so Alfresco cannot find a specific piece of content it needs during startup (its version information).

**Comment by maciass2008** [comment]
Yes "dir.root" points to an existing folder ( dir.root=D:/Alfresco/alf_data ) 
i remove all default content store content and create a new database schema 
so i have no data or content in my default content store 
if i try to start alfresco without adding the following lines to my alfresco-global.properties
 simpleContentStores.enabled=true
simpleContentStores.customStores=myCustomFileStore
simpleContentStores.rootStore=myCustomFileStore
simpleContentStores.customStore.myCustomFileStore.type=standardFileStore
simpleContentStores.customStore.myCustomFileStore.value.rootDirectory=${dir.root}/myContentStore
simpleContentStores.customStore.myCustomFileStore.value.deleteEmptyDirs=true
simpleContentStores.customStore.myCustomFileStore.value.fixedLimit=104857600
All work fine
but when i add them i receive the error I told you about!

**Comment by maciass2008** [comment]
you are right
I did not notice that even if the default content store is empty it contains some files that are created automatically after the first start of alfresco
when i removed them to my ${dir.root}/myContentStore alfresco start correctly and and i was able to add a document in this new content store
But if i add more than one content store how can i managed them?
how can i choose for example that file A is loaded in content store A and file B is loaded in content store B?
thank you

**Comment by AFaust** [comment]
That is where the routing content stores come into play (and the configuration becomes a bit more complex). E.g. with a site-routing store you can choose that file A/B is stored in location A/B based on the site in which A/B is located. Depending on what type of storage you want to address you could use the simpler [site-routing file store](https://github.com/Acosix/alfresco-simple-content-stores/wiki/Site-Routing-File-Store) or opt for the generic [site-routing store](https://github.com/Acosix/alfresco-simple-content-stores/wiki/Site-Routing-Store) which needs to be backed by other stores, building a chain/tree of content stores (i.e. including compression) until the last store is responsible for actually writing the file to some place.

**Comment by maciass2008** [comment]
I just implemented it and everything works properly
thank you so much for your reply
