### ISSUE TITLE
Installation problem: Model tracking failed  org.alfresco.error.AlfrescoRuntimeException: 08050000 GetModelsDiff return status is 404

### ISSUE THREAD

**Issue by billydekid** [Acosix/alfresco-simple-content-stores#45]
Hi @AFaust,

Continuing to enable an encrypting store on my Community edition 5.2, I use prebuilt "acosix-utility-core" from Maven central (AMPs) as you suggest (https://github.com/Acosix/alfresco-utility/issues/14#issuecomment-2317341681):

1. de.acosix.alfresco.utility.core.repo-1.4.3.amp
2. de.acosix.alfresco.utility.core.share-1.4.3.amp

Then after that install the simple content store: de.acosix.alfresco.simplecontentstores.repo-1.2.4.amp
The installation of the three modules above was successful.

Then I try to start alfresco but got following "Solr error".
Could you please share what I missed or any specific manual documentation when enabling the "Encrypting Content Store" module?

```
INFO: Starting ProtocolHandler ["http-apr-8080"]
Sep 05, 2024 4:32:25 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["ajp-apr-8009"]
Sep 05, 2024 4:32:25 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-bio-8443"]
Sep 05, 2024 4:32:25 PM org.apache.catalina.startup.Catalina start
INFO: Server startup in 52882 ms
2024-09-05 16:32:25,931  ERROR [solr.tracker.AbstractTracker] [org.alfresco.solr.AlfrescoCoreAdminHandler@ac1abfd_Worker-2] Model tracking failed
 org.alfresco.error.AlfrescoRuntimeException: 08050000 GetModelsDiff return status is 404
        at org.alfresco.solr.client.SOLRAPIClient.getModelsDiff(SOLRAPIClient.java:1181)
        at org.alfresco.solr.tracker.ModelTracker.trackModelsImpl(ModelTracker.java:256)
        at org.alfresco.solr.tracker.ModelTracker.trackModels(ModelTracker.java:214)
        at org.alfresco.solr.tracker.ModelTracker.ensureFirstModelSync(ModelTracker.java:236)
        at org.alfresco.solr.tracker.CoreWatcherJob.registerForCore(CoreWatcherJob.java:145)
        at org.alfresco.solr.tracker.CoreWatcherJob.execute(CoreWatcherJob.java:82)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:216)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:563)
2024-09-05 16:32:26,153  ERROR [solr.tracker.AbstractTracker] [org.alfresco.solr.AlfrescoCoreAdminHandler@ac1abfd_Worker-2] Model tracking failed
 org.alfresco.error.AlfrescoRuntimeException: 08050002 GetModelsDiff return status is 404
        at org.alfresco.solr.client.SOLRAPIClient.getModelsDiff(SOLRAPIClient.java:1181)
        at org.alfresco.solr.tracker.ModelTracker.trackModelsImpl(ModelTracker.java:256)
        at org.alfresco.solr.tracker.ModelTracker.trackModels(ModelTracker.java:214)
        at org.alfresco.solr.tracker.ModelTracker.ensureFirstModelSync(ModelTracker.java:236)
        at org.alfresco.solr.tracker.CoreWatcherJob.registerForCore(CoreWatcherJob.java:145)
        at org.alfresco.solr.tracker.CoreWatcherJob.execute(CoreWatcherJob.java:82)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:216)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:563)
2024-09-05 16:32:26,200  ERROR [solr.tracker.AbstractTracker] [org.alfresco.solr.AlfrescoCoreAdminHandler@ac1abfd_Worker-3] Tracking failed
 org.alfresco.error.AlfrescoRuntimeException: 08050001 GetModelsDiff return status is 404
        at org.alfresco.solr.client.SOLRAPIClient.getModelsDiff(SOLRAPIClient.java:1181)
        at org.alfresco.solr.tracker.ModelTracker.trackModelsImpl(ModelTracker.java:256)
        at org.alfresco.solr.tracker.ModelTracker.trackModels(ModelTracker.java:214)
        at org.alfresco.solr.tracker.ModelTracker.doTrack(ModelTracker.java:174)
        at org.alfresco.solr.tracker.AbstractTracker.track(AbstractTracker.java:190)
        at org.alfresco.solr.tracker.TrackerJob.execute(TrackerJob.java:54)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:216)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:563)
2024-09-05 16:32:30,111  ERROR [solr.tracker.AbstractTracker] [org.alfresco.solr.AlfrescoCoreAdminHandler@ac1abfd_Worker-7] Tracking failed
 org.alfresco.error.AlfrescoRuntimeException: 08050004 api/solr/aclchangesets return status:404
        at org.alfresco.solr.client.SOLRAPIClient.getAclChangeSets(SOLRAPIClient.java:169)
        at org.alfresco.solr.tracker.AclTracker.checkRepoAndIndexConsistency(AclTracker.java:354)
        at org.alfresco.solr.tracker.AclTracker.trackRepository(AclTracker.java:320)
        at org.alfresco.solr.tracker.AclTracker.doTrack(AclTracker.java:111)
        at org.alfresco.solr.tracker.AbstractTracker.track(AbstractTracker.java:190)
        at org.alfresco.solr.tracker.TrackerJob.execute(TrackerJob.java:54)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:216)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:563)
2024-09-05 16:32:30,126  ERROR [solr.tracker.AbstractTracker] [org.alfresco.solr.AlfrescoCoreAdminHandler@ac1abfd_Worker-6] Tracking failed
 org.alfresco.error.AlfrescoRuntimeException: 08050003 api/solr/aclchangesets return status:404
        at org.alfresco.solr.client.SOLRAPIClient.getAclChangeSets(SOLRAPIClient.java:169)
        at org.alfresco.solr.tracker.AclTracker.checkRepoAndIndexConsistency(AclTracker.java:354)
        at org.alfresco.solr.tracker.AclTracker.trackRepository(AclTracker.java:320)
        at org.alfresco.solr.tracker.AclTracker.doTrack(AclTracker.java:111)
        at org.alfresco.solr.tracker.AbstractTracker.track(AbstractTracker.java:190)
        at org.alfresco.solr.tracker.TrackerJob.execute(TrackerJob.java:54)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:216)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:563)

```
Thank you in advance,

**Comment by billydekid** [comment]
PS: I successfully install "alfresco-utility" and activate alfresco-simple-content-stores in Alfresco Community v23.2.0.

**Comment by AFaust** [comment]
Without having the logs for the ACS repository that show why it failed to start up (that is most often the cause for the 404 error), I can't make any suggestions.
